function [fitresult, gof] = poly320Fit(X, Y)
%CREATEFIT(X,Y)
%  Create a fit.
%
%  Data for 'untitled fit 1' fit:
%      X Input : X
%      Y Output: Y
%  Output:
%      fitresult : a fit object representing the fit.
%      gof : structure with goodness-of fit info.
%
%  See also FIT, CFIT, SFIT.

%  Auto-generated by MATLAB on 30-Oct-2018 17:18:10


%% Fit: 'untitled fit 1'.
[xData, yData] = prepareCurveData( X, Y );

% Set up fittype and options.
ft = fittype( 'poly3' );
opts = fitoptions('Method', 'LinearLeastSquares');
opts.Lower = [-Inf -Inf 0 -Inf];
%opts.Lower = [-Inf -Inf 0 0]; %Use this line to fit A = 0;
%opts.Upper = [Inf Inf 0 0];
opts.Robust = 'LAR';
opts.Upper = [Inf Inf 0 0]; % A is small than 0. -logP(measured) smaller than -logP(real)

% Fit model to data.
[fitresult, gof] = fit( xData, yData, ft, opts);

% Plot fit with data.
figure( 'Name', 'untitled fit 1' );
h = plot( fitresult, xData, yData );
legend( h, 'Y vs. X', 'untitled fit 1', 'Location', 'NorthEast' );
% Label axes
xlabel X
ylabel Y
grid on


